Add waveform_gen.py file to support waveform data generation.
analogdevicesinc/genalyzer pull request #26
Opened 2023-10-11 13:26 UTC by SaikiranGudla

Add APIs to generate data for various waveforms.

2023-10-11 13:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/genalyzer?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/genalyzer?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/genalyzer?pullRequest=26) it.</sub>

2023-10-12 20:33 UTC, tfcollins requested changes
1. Can we make this a sub-namespace of genalyzer itself? So we can just import genalyzer and get these utils with something like:
```python
from genalyzer import WaveformGen
```

2. Can you update the pymodules and dependencies within setup.py

3. Can you add some basic testing

2023-10-13 11:35 UTC, SaikiranGudla commented
> 1. Can we make this a sub-namespace of genalyzer itself? So we can just import genalyzer and get these utils with something like:
> 
> ```python
> from genalyzer import WaveformGen
> ```
> 
> 2. Can you update the pymodules and dependencies within setup.py
> 3. Can you add some basic testing

I think instead of a different module named waveform_gen, I can add the WaveformGen class and its methods, which eventually call the genalyzer APIs in the genalyzer.py file itself. In this way, one can import WaveformGen from the genalyzer module. Does it make sense?
Will also update setup.py file and testing.

2023-10-17 05:38 UTC, SaikiranGudla commented
May I know if there are any comments from the reviewers?

2023-10-26 23:22 UTC, merged